//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IM_MasterData
    {
        public int Id { get; set; }
        public string MasterName { get; set; }
        public string Descrption { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
