//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IM_SUPPLIER
    {
        public int ID { get; set; }
        public string BusinessName { get; set; }
        public string Name { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public Nullable<int> PlantId { get; set; }
        public Nullable<int> CoreTypeId { get; set; }
        public string EmailId { get; set; }
        public string ExpectedDays { get; set; }
        public string GSTno { get; set; }
        public string SACcode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
