//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Resources.Communication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryManagement.Resources.Communication.MailTemplates", typeof(MailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear [[[Name]]],&lt;br/&gt;&lt;br/&gt;Your password has been changed successfully&lt;br/&gt;&lt;br/&gt;Thanks,&lt;br/&gt;Inventory Management Team.
        /// </summary>
        public static string ChangePassword_Body {
            get {
                return ResourceManager.GetString("ChangePassword_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password successfully.
        /// </summary>
        public static string ChangePassword_Subject {
            get {
                return ResourceManager.GetString("ChangePassword_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear [[[Name]]],&lt;br/&gt;&lt;br/&gt; Click &lt;a href=&apos;[[[Link]]]&apos;&gt;here&lt;/a&gt; to reset your password &lt;br/&gt; &lt;br/&gt;&lt;br/&gt;Thanks,&lt;br/&gt;Inventory Management Team.
        /// </summary>
        public static string ForgotPassword_Body {
            get {
                return ResourceManager.GetString("ForgotPassword_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ForgotPassword_Subject {
            get {
                return ResourceManager.GetString("ForgotPassword_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:57625/.
        /// </summary>
        public static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear [[[Name]]],&lt;br/&gt;&lt;br/&gt;Your registration has been successfully.&lt;br/&gt;You canc click &lt;a href=&apos;[[[Link]]]&apos;&gt;here&lt;/a&gt; to login and below are the credentials.&lt;br/&gt;&lt;br/&gt;UserName: [[[UserName]]] &lt;br/&gt;Password: [[[Password]]]&lt;br/&gt;&lt;br/&gt;Thanks,&lt;br/&gt;Inventory Management Team.
        /// </summary>
        public static string NewRegistration_Body {
            get {
                return ResourceManager.GetString("NewRegistration_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Successfully.
        /// </summary>
        public static string NewRegistration_Subject {
            get {
                return ResourceManager.GetString("NewRegistration_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account/ResetPassword?userid=[[[UserID]]].
        /// </summary>
        public static string ResetPasswordLink {
            get {
                return ResourceManager.GetString("ResetPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        public static string SmtpClient_Host {
            get {
                return ResourceManager.GetString("SmtpClient_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sanjeevi3940.
        /// </summary>
        public static string SmtpClient_Password {
            get {
                return ResourceManager.GetString("SmtpClient_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        public static string SmtpClient_Port {
            get {
                return ResourceManager.GetString("SmtpClient_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snaresh1785@gmail.com.
        /// </summary>
        public static string SmtpClient_UserName {
            get {
                return ResourceManager.GetString("SmtpClient_UserName", resourceCulture);
            }
        }
    }
}
